package objectsql

import sdkobjectsql "github.com/domainry/domainry-report-sdk/query/objectsql"

var NormalizeParameters = sdkobjectsql.NormalizeParameters
var NormalizeDeclaredParameters = sdkobjectsql.NormalizeDeclaredParameters
var SafeCrossWorkspaceAggregatePlan = sdkobjectsql.SafeCrossWorkspaceAggregatePlan
var ExpressionHasAggregate = sdkobjectsql.ExpressionHasAggregate
var CompileReportObjectSQL = sdkobjectsql.CompileReportObjectSQL
var DiscoverReportObjectSQLSources = sdkobjectsql.DiscoverReportObjectSQLSources
var ReportObjectSQLPlanSingleRow = sdkobjectsql.ReportObjectSQLPlanSingleRow

const (
	ReportObjectSQLDefaultLimitRows = sdkobjectsql.ReportObjectSQLDefaultLimitRows
	ReportObjectSQLMaximumLimitRows = sdkobjectsql.ReportObjectSQLMaximumLimitRows
)
